// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp, auth } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful to verify connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/index.ts
var SUPABASE_AUTH_ISSUER = "https://ynqpvyimpqovcbqtcntw.supabase.co/auth/v1";
var mcp_default = defineMcp({
  name: "bussola-mcp",
  title: "B\xFAssola MCP",
  version: "0.1.0",
  instructions: "Tools for the B\xFAssola pedagogical monitoring platform. Use `echo` to verify connectivity.",
  // Require a verified OAuth access token issued by the app's auth server.
  auth: auth.oauth.issuer({
    issuer: SUPABASE_AUTH_ISSUER,
    acceptedAudiences: ["authenticated"],
    resourceName: "B\xFAssola MCP"
  }),
  tools: [echo_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
