
-- Insert instrument_fields for observacao_aula_redes (9 criteria, scale 1-4)
INSERT INTO public.instrument_fields (form_type, field_key, label, description, field_type, scale_min, scale_max, scale_labels, dimension, sort_order, is_required) VALUES
('observacao_aula_redes', 'nota_criterio_1', 'As intervenções estavam alinhadas ao caderno e à faixa de desempenho do grupo?', 'Existem estudantes em diferentes níveis de proficiência dentro de um mesmo agrupamento.', 'rating', 1, 4, '[{"value":1,"label":"Insuficiente"},{"value":2,"label":"Em Desenvolvimento"},{"value":3,"label":"Consolidado"},{"value":4,"label":"Avançado"}]'::jsonb, 'Critérios de Observação', 1, true),
('observacao_aula_redes', 'nota_criterio_2', 'O objetivo de aprendizagem estava claro e foi comunicado aos estudantes?', 'O aluno precisa saber o que está aprendendo e por que isso é importante para o seu progresso.', 'rating', 1, 4, '[{"value":1,"label":"Insuficiente"},{"value":2,"label":"Em Desenvolvimento"},{"value":3,"label":"Consolidado"},{"value":4,"label":"Avançado"}]'::jsonb, 'Critérios de Observação', 2, true),
('observacao_aula_redes', 'nota_criterio_3', 'O professor demonstrou repertório para explicar o conteúdo de diferentes formas?', 'A metodologia deve ser o veículo que transporta o aluno do não saber ao saber.', 'rating', 1, 4, '[{"value":1,"label":"Insuficiente"},{"value":2,"label":"Em Desenvolvimento"},{"value":3,"label":"Consolidado"},{"value":4,"label":"Avançado"}]'::jsonb, 'Critérios de Observação', 3, true),
('observacao_aula_redes', 'nota_criterio_4', 'O professor utilizou metodologias que favorecem a aprendizagem?', 'A caixa de ferramentas do professor. A estratégia alcança quem tem dificuldade?', 'rating', 1, 4, '[{"value":1,"label":"Insuficiente"},{"value":2,"label":"Em Desenvolvimento"},{"value":3,"label":"Consolidado"},{"value":4,"label":"Avançado"}]'::jsonb, 'Critérios de Observação', 4, true),
('observacao_aula_redes', 'nota_criterio_5', 'A maioria dos alunos participou ativamente da aula?', 'Engajamento coletivo e a capacidade do professor de converter o plano em uma experiência compartilhada.', 'rating', 1, 4, '[{"value":1,"label":"Insuficiente"},{"value":2,"label":"Em Desenvolvimento"},{"value":3,"label":"Consolidado"},{"value":4,"label":"Avançado"}]'::jsonb, 'Critérios de Observação', 5, true),
('observacao_aula_redes', 'nota_criterio_6', 'O professor fez intervenções que apoiam a compreensão?', 'A capacidade do professor de atuar sobre a dúvida, oferecendo suportes para superar obstáculos cognitivos.', 'rating', 1, 4, '[{"value":1,"label":"Insuficiente"},{"value":2,"label":"Em Desenvolvimento"},{"value":3,"label":"Consolidado"},{"value":4,"label":"Avançado"}]'::jsonb, 'Critérios de Observação', 6, true),
('observacao_aula_redes', 'nota_criterio_7', 'O professor verificou a compreensão dos estudantes?', 'Monitoramento constante (avaliação formativa) para saber se a turma está acompanhando antes de avançar.', 'rating', 1, 4, '[{"value":1,"label":"Insuficiente"},{"value":2,"label":"Em Desenvolvimento"},{"value":3,"label":"Consolidado"},{"value":4,"label":"Avançado"}]'::jsonb, 'Critérios de Observação', 7, true),
('observacao_aula_redes', 'nota_criterio_8', 'O clima da sala é de colaboração, respeito mútuo e favorável à aprendizagem?', 'Segurança psicológica e respeito. O aluno precisa se sentir seguro para errar.', 'rating', 1, 4, '[{"value":1,"label":"Insuficiente"},{"value":2,"label":"Em Desenvolvimento"},{"value":3,"label":"Consolidado"},{"value":4,"label":"Avançado"}]'::jsonb, 'Critérios de Observação', 8, true),
('observacao_aula_redes', 'nota_criterio_9', 'O professor gerenciou bem o tempo para atividades e dúvidas?', 'Equilíbrio entre cumprir a sequência didática e garantir que os momentos de prática e dúvida não sejam atropelados.', 'rating', 1, 4, '[{"value":1,"label":"Insuficiente"},{"value":2,"label":"Em Desenvolvimento"},{"value":3,"label":"Consolidado"},{"value":4,"label":"Avançado"}]'::jsonb, 'Critérios de Observação', 9, true),

-- Insert instrument_fields for encontro_eteg_redes (8 items, scale 0-2)
('encontro_eteg_redes', 'item_1', 'Os gestores e/ou equipe técnica utilizam regularmente a Plataforma Trajetórias para acompanhar a escola?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 1, true),
('encontro_eteg_redes', 'item_2', 'Os gestores e/ou equipe técnica demonstram entendimento sobre as discussões dos dados de aprendizagem?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 2, true),
('encontro_eteg_redes', 'item_3', 'O quórum de gestores e/ou equipe técnica na formação foi igual ou superior a 75%?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 3, true),
('encontro_eteg_redes', 'item_4', 'Os gestores e/ou equipe técnica incorporaram à sua prática (rotina) a metodologia de gestão para aprendizagem (modelo SAEB)?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 4, true),
('encontro_eteg_redes', 'item_5', 'Os gestores mantêm uma rotina de reunião com CP para planejar a caminhada pedagógica?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 5, true),
('encontro_eteg_redes', 'item_6', 'Os gestores/equipe técnica se apoiam nos dados das avaliações para fazer os acompanhamentos (caminhada pedagógica) junto aos professores?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 6, true),
('encontro_eteg_redes', 'item_7', 'A coordenação pedagógica estabelece junto aos docentes planos de ação com base nos dados das avaliações?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 7, true),
('encontro_eteg_redes', 'item_8', 'Há evidências de que os dados das avaliações orientam as decisões pedagógicas da escola?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 8, true),

-- Insert instrument_fields for encontro_professor_redes (8 items, scale 0-2)
('encontro_professor_redes', 'item_1', 'Todos os professores participam ativamente da formação?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 1, true),
('encontro_professor_redes', 'item_2', 'Os professores demonstram clareza sobre os objetivos da formação para 2026?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 2, true),
('encontro_professor_redes', 'item_3', 'O quórum de professores nessa formação foi igual ou superior a 75% no dia do encontro formativo?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 3, true),
('encontro_professor_redes', 'item_4', 'Há participação de outros atores que não de professores de 4º anos?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 4, true),
('encontro_professor_redes', 'item_5', 'O professor utiliza efetivamente o material didático adotado pela rede durante a aula?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 5, true),
('encontro_professor_redes', 'item_6', 'O professor acessa ou tem conhecimento dos dados da Plataforma Trajetórias que apresenta o resultado das aprendizagens dos estudantes?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 6, true),
('encontro_professor_redes', 'item_7', 'Há evidências de que os resultados da avaliação orientam o planejamento para intervenções pedagógicas em sala de aula?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 7, true),
('encontro_professor_redes', 'item_8', 'O conteúdo da pauta/atividade selecionada da avaliação atendeu a demanda dos professores?', NULL, 'rating', 0, 2, '[{"value":0,"label":"Não implementado"},{"value":1,"label":"Parcialmente implementado"},{"value":2,"label":"Implementado conforme previsto"}]'::jsonb, 'Itens de Verificação', 8, true);
