GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.is_gestor(uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.is_manager(uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.is_admin_or_gestor(uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.is_observer(uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.is_operational(uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.is_local_user(uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.get_user_role(uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.user_has_programa(uuid, text) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.user_has_entidade(uuid, uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.shares_programa(uuid, uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.shares_entidade(uuid, uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.gestor_has_programa(uuid, text) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.gestor_can_view_escola(uuid, uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.gestor_can_view_professor(uuid, uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.gestor_can_view_programacao(uuid, uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.gestor_can_view_registro(uuid, uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.user_can_view_redes_municipio(uuid, text) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.user_has_escola_via_programa(uuid, uuid) TO authenticated, anon, service_role;
GRANT EXECUTE ON FUNCTION public.user_has_full_data_access(uuid, uuid, text[]) TO authenticated, anon, service_role;