
-- Insert instrument_fields for registro_apoio_presencial
INSERT INTO public.instrument_fields (form_type, field_key, label, description, field_type, scale_min, scale_max, scale_labels, dimension, sort_order, is_required, metadata) VALUES

-- DIMENSÃO: Planejamento e Domínio do Conteúdo e Recursos Pedagógicos (4 rating + 1 textarea)
('registro_apoio_presencial', 'plan_curriculo', 'O conteúdo é alinhado ao currículo (competências e habilidades) e possui foco nos pré-requisitos para que o aluno avance', 'A aula aborda o que é essencial para o ano/ciclo, previsto no currículo, respeitando a progressão necessária para a recomposição.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"Além do alinhamento curricular, o professor integrou diferentes habilidades e conteúdos, adaptando em tempo real para sanar lacunas de anos anteriores identificadas durante a aula."},{"value":2,"label":"Efetivo","description":"O conteúdo estava alinhado às habilidades do currículo e o professor focou nos pré-requisitos necessários para que os alunos avancem."},{"value":1,"label":"Pouco efetivo","description":"O conteúdo estava alinhado às habilidades do currículo, mas foi abordado de forma isolada, superficial ou sem foco nos pré-requisitos necessários para que os alunos avancem."},{"value":0,"label":"Nada efetivo","description":"O conteúdo trabalhado não possui conexão clara com as habilidades do currículo e/ou estava desalinhado ao nível de desenvolvimento da turma."}]'::jsonb, 'Planejamento e Domínio do Conteúdo e Recursos Pedagógicos', 1, true, null),

('registro_apoio_presencial', 'plan_objetivo', 'O objetivo da aprendizagem da aula é evidente e significado', 'A apresentação do objetivo da aprendizagem oferece clareza aos estudantes sobre o que será aprendido e porquê.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"O objetivo foi apresentado, significado e retomado durante toda a aula como bússola, conectando ao que os estudantes já sabem e articulando as atividades. Os estudantes compreenderam o sentido do que estão fazendo e aonde precisam chegar."},{"value":2,"label":"Efetivo","description":"O objetivo foi apresentado pelo professor e conectado ao que os estudantes já sabem. Houve coerência entre o que foi proposto e a aprendizagem esperada. Os estudantes compreenderam o sentido da aprendizagem esperada."},{"value":1,"label":"Pouco efetivo","description":"O objetivo foi apresentado pelo professor, de forma técnica ou burocrática, sem que os estudantes compreendessem o que deverão ser capazes de fazer e qual o sentido da aprendizagem esperada."},{"value":0,"label":"Nada efetivo","description":"O objetivo não foi apresentado pelo professor e nem pôde ser identificado a partir das explicações e atividades propostas ou ainda foi confundido com a simples execução de uma tarefa."}]'::jsonb, 'Planejamento e Domínio do Conteúdo e Recursos Pedagógicos', 2, true, null),

('registro_apoio_presencial', 'plan_dominio', 'O domínio conceitual permite a realização de explicações contextualizadas, exemplificações e adaptações', 'Conexão entre o que o estudante está aprendendo e o que ele já sabe e/ou ao seu cotidiano.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"As explicações extrapolaram o material orientador, houve o estabelecimento de relações com outros objetos de conhecimento, exemplos variados e contextualizados na vida dos estudantes. O professor manteve coerência conceitual para resolução de dúvidas e para realização de adaptações para sanar lacunas de aprendizagem."},{"value":2,"label":"Efetivo","description":"As explicações foram realizadas de acordo com o material orientador, o professor não encontrou dificuldades na resolução de dúvidas, exemplificação ou contextualização na vida dos estudantes."},{"value":1,"label":"Pouco efetivo","description":"As explicações foram realizadas de acordo com o material orientador, o professor encontrou dificuldades nas exemplificações, na contextualização na vida dos estudantes ou nas adaptações para sanar lacunas de aprendizagem."},{"value":0,"label":"Nada efetivo","description":"As explicações foram superficiais, desconectadas do material orientador, com presença de equívocos conceituais para resolução de dúvidas, exemplificação ou adaptações."}]'::jsonb, 'Planejamento e Domínio do Conteúdo e Recursos Pedagógicos', 3, true, null),

('registro_apoio_presencial', 'plan_recursos', 'A utilização dos recursos pedagógicos favorece a aprendizagem', 'Os recursos utilizados apoiam aprendizagem de forma intencional e não apenas para cumprir metas ou seguir roteiros de forma mecânica.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"O professor demonstrou preparo e domínio na utilização dos recursos pedagógicos previstos nas orientações dos materiais, além de trazer outros para conduzir a turma nas atividades ou realizar as adaptações necessárias. Ficou clara a conexão do uso dos recursos para o desenvolvimento das aprendizagens previstas."},{"value":2,"label":"Efetivo","description":"O professor utilizou os recursos pedagógicos orientados pelo material, apresentando conhecimento básico sobre eles. Ficou clara a conexão do uso dos recursos para o desenvolvimento das aprendizagens previstas."},{"value":1,"label":"Pouco efetivo","description":"O professor utilizou os recursos pedagógicos orientados pelo material, com pouca segurança ou com dificuldade para utilizá-los. Não ficou clara a conexão do uso dos recursos para o desenvolvimento das aprendizagens previstas."},{"value":0,"label":"Nada efetivo","description":"Não houve utilização de recursos ou os recursos foram utilizados de forma inadequada ou desconectada das aprendizagens esperadas. O professor apresenta dificuldades na utilização dos recursos."}]'::jsonb, 'Planejamento e Domínio do Conteúdo e Recursos Pedagógicos', 4, true, null),

('registro_apoio_presencial', 'plan_evidencias', 'Registre as evidências referentes a este foco de observação', null, 'textarea', null, null, null, 'Planejamento e Domínio do Conteúdo e Recursos Pedagógicos', 5, true, null),

-- DIMENSÃO: Estratégias de Aprendizagem (5 rating + 1 textarea)
('registro_apoio_presencial', 'estr_conteudo_organizado', 'O conteúdo foi trabalhado de maneira organizada e as transições entre as partes da aula garantiram as atividades previstas', 'Em recomposição, o tempo é ouro e a explicação não pode gerar mais confusão, para isso a organização e objetividade do conteúdo é fundamental.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"O professor trabalhou o conteúdo em uma sequência lógica e estruturada, que extrapolou as orientações do material, e garantiu uma transição fluida entre as partes da aula e a realização das atividades previstas, mesmo com a realização de adaptações para superar as lacunas de aprendizagem."},{"value":2,"label":"Efetivo","description":"O professor trabalhou o conteúdo, em sequência lógica, orientada pelo material, garantindo transições entre as partes da aula adequadas e a realização das atividades previstas."},{"value":1,"label":"Pouco efetivo","description":"O professor trabalhou o conteúdo, na sequência orientada pelo material, porém sem garantir a realização das atividades previstas. As transições entre as partes da aula foram lentas."},{"value":0,"label":"Nada efetivo","description":"O professor trabalhou o conteúdo de forma confusa, com excesso/falta de informações ou falta de conexão com os estudantes. A transição entre as partes da aula foi lenta."}]'::jsonb, 'Estratégias de Aprendizagem', 6, true, null),

('registro_apoio_presencial', 'estr_abordagem_lacunas', 'A abordagem e as estratégias utilizadas alcançam os estudantes com lacunas de aprendizagem', 'A diversificação de abordagens na turma é fundamental para quem possui lacunas de aprendizagem possa aprender.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"O professor utilizou uma abordagem heterogênea para trabalhar com a turma, diversificando estratégias e atividades e apoiando a superação das barreiras de aprendizagem da maioria dos estudantes."},{"value":2,"label":"Efetivo","description":"O professor utilizou uma abordagem heterogênea para trabalhar com a turma, diversificando estratégias e atividades, buscando apoiar nas dificuldades individuais de alguns estudantes."},{"value":1,"label":"Pouco efetivo","description":"O professor utilizou uma abordagem única para a turma, oferecendo as mesmas explicações e atividades para todos, buscando apoiar nas dificuldades individuais de alguns estudantes."},{"value":0,"label":"Nada efetivo","description":"O professor utilizou uma abordagem única para a turma, oferecendo as mesmas explicações e atividades para todos, com pouco foco na superação das dificuldades de aprendizagem existentes."}]'::jsonb, 'Estratégias de Aprendizagem', 7, true, null),

('registro_apoio_presencial', 'estr_aprendizagem_ativa', 'As estratégias de aprendizagem utilizadas garantem a participação ativa dos estudantes', 'Aprendizagem ativa é quando o estudante é protagonista da construção do conhecimento.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"O professor utilizou estratégias de aprendizagem ativa durante toda a aula, promovendo a compreensão de conceitos complexos. Os alunos realizaram tarefas mão na massa. Houve variação de estratégias quando os alunos não estavam atingindo o objetivo. Centralidade dos estudantes na construção do conhecimento."},{"value":2,"label":"Efetivo","description":"O professor utilizou estratégias para promover a aprendizagem ativa na maior parte da aula. Os alunos realizaram tarefas mão na massa. Centralidade dos estudantes na construção do conhecimento."},{"value":1,"label":"Pouco efetivo","description":"O professor realizou exposição dialogada, na maior parte da aula, garantindo a participação ativa dos estudantes em momentos pontuais. Os alunos realizaram tarefas mecânicas de cópia ou repetição. Centralidade do professor na construção do conhecimento."},{"value":0,"label":"Nada efetivo","description":"O professor utilizou estratégias passivas de aprendizagem na maior parte da aula, como aula expositiva. Centralidade do professor na construção do conhecimento."}]'::jsonb, 'Estratégias de Aprendizagem', 8, true, null),

('registro_apoio_presencial', 'estr_questionamentos', 'Os questionamentos realizados aos estudantes promovem a reflexão', 'O uso de perguntas abertas que desafiam o aluno a pensar, em vez de apenas fornecer respostas curtas ou memorizadas.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"O professor utilizou perguntas que geram um efeito cascata: a pergunta do professor estimulou os alunos a questionarem uns aos outros e a aprofundarem a discussão."},{"value":2,"label":"Efetivo","description":"O professor utilizou perguntas que estimulam os alunos a explicar seus raciocínios, comparar ideias e justificar suas respostas na maior parte da aula."},{"value":1,"label":"Pouco efetivo","description":"O professor utilizou perguntas que estimulam a memória (o quê), mas não avançam para o porquê ou como na maior parte da aula. Muitas vezes, ele mesmo responde às suas perguntas."},{"value":0,"label":"Nada efetivo","description":"O professor não fez perguntas reflexivas, apenas perguntas objetivas de resposta sim ou não e de resgate de memória, que não exigem esforço de raciocínio durante a aula."}]'::jsonb, 'Estratégias de Aprendizagem', 9, true, null),

('registro_apoio_presencial', 'estr_ajustes_pedagogicos', 'As respostas dos estudantes norteiam a realização de ajustes pedagógicos', 'A flexibilidade do professor em abandonar o roteiro planejado para atender a uma necessidade real demonstrada pelos alunos durante a aula.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"O professor utilizou o erro como oportunidade de aprendizagem, transformando a dúvida de um aluno em um novo desafio para a turma e adaptando a aula de forma orgânica e fluida."},{"value":2,"label":"Efetivo","description":"O professor propôs uma nova forma de explicar e/ou alterou as atividades e o ritmo da aula para garantir que a turma avance ao notar erros comuns ou dúvidas persistentes."},{"value":1,"label":"Pouco efetivo","description":"O professor trabalhou os erros ou dificuldades apresentadas pelos alunos, repetindo explicações, sem alteração de estratégia para oferecer uma abordagem diferente."},{"value":0,"label":"Nada efetivo","description":"O professor não trabalhou os erros ou dificuldades apresentadas pelos alunos e manteve o ritmo, mesmo quando os estudantes demonstraram estar perdidos."}]'::jsonb, 'Estratégias de Aprendizagem', 10, true, null),

('registro_apoio_presencial', 'estr_evidencias', 'Registre as evidências referentes a este foco de observação', null, 'textarea', null, null, null, 'Estratégias de Aprendizagem', 11, true, null),

-- DIMENSÃO: Gestão de Sala de Aula (7 rating + 1 textarea)
('registro_apoio_presencial', 'gestao_engajamento', 'O engajamento dos estudantes para iniciar a aula garante apoio à realização das atividades previstas', 'Engajar os estudantes para iniciar a aula em curto espaço de tempo apoia a garantia de desenvolvimento das atividades planejadas.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"O professor utilizou até 5 min para iniciar a aula e engajar os alunos."},{"value":2,"label":"Efetivo","description":"O professor utilizou até 10 min para iniciar a aula e engajar os alunos."},{"value":1,"label":"Pouco efetivo","description":"O professor utilizou até 15 minutos para iniciar a aula e engajar os alunos."},{"value":0,"label":"Nada efetivo","description":"O professor utilizou mais de 15 minutos para iniciar a aula e engajar os alunos."}]'::jsonb, 'Gestão de Sala de Aula', 12, true, null),

('registro_apoio_presencial', 'gestao_adaptacao', 'As dificuldades ou avanço dos estudantes são norteadores para adaptação de ritmo e/ou atividades', 'Adaptação de aula diz respeito a ajustar o ritmo, as explicações, os exemplos e atividades a partir do que observa sobre a turma na própria aula.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"O professor identificou dificuldades e avanços dos estudantes e realizou adaptação de ritmo, explicações e atividades."},{"value":2,"label":"Efetivo","description":"O professor identificou dificuldades e avanços dos estudantes, ao longo da aula, e realizou algumas adaptações de atividades."},{"value":1,"label":"Pouco efetivo","description":"O professor identificou dificuldades e avanços dos estudantes, ao longo da aula, mas não houve adaptações."},{"value":0,"label":"Nada efetivo","description":"O professor não identificou dificuldades ou avanços dos estudantes, ao longo da aula, para adaptação de ritmo e atividades."}]'::jsonb, 'Gestão de Sala de Aula', 13, true, null),

('registro_apoio_presencial', 'gestao_questionamentos', 'Os questionamentos realizados aos estudantes promovem a reflexão', 'O uso de perguntas abertas que desafiam o aluno a pensar.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"O professor utilizou perguntas que geram um efeito cascata: a pergunta do professor estimulou os alunos a questionarem uns aos outros e a aprofundarem a discussão."},{"value":2,"label":"Efetivo","description":"O professor utilizou perguntas que estimulam os alunos a explicar seus raciocínios, comparar ideias e justificar suas respostas na maior parte da aula."},{"value":1,"label":"Pouco efetivo","description":"O professor utilizou perguntas que estimulam a memória, mas não avançam para o porquê ou como na maior parte da aula."},{"value":0,"label":"Nada efetivo","description":"O professor não fez perguntas reflexivas, apenas perguntas objetivas de resposta sim ou não e de resgate de memória."}]'::jsonb, 'Gestão de Sala de Aula', 14, true, null),

('registro_apoio_presencial', 'gestao_tempo', 'O gerenciamento do tempo garante desenvolvimento da sequência didática, resolução de dúvidas e sistematização de aprendizagens', 'O equilíbrio entre cumprir a sequência didática e garantir que os momentos de prática e dúvida não sejam atropelados é fundamental para a aprendizagem.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"O professor realizou a gestão do tempo de modo a maximizar o tempo de aprendizagem ativa. Mesmo com imprevistos o professor garantiu o essencial da retomada, introdução, desenvolvimento e sistematização final do conteúdo. Foi possível tirar as dúvidas dos estudantes e realizar atividades práticas."},{"value":2,"label":"Efetivo","description":"O professor distribuiu o tempo da aula entre a prática guiada, prática autônoma e sistematização de aprendizagem. Os tempos foram suficientes para as tarefas e explicações."},{"value":1,"label":"Pouco efetivo","description":"O professor cumpriu o cronograma da aula mas de forma apressada e superficial. Nem todos os momentos importantes da aula aconteceram. Os tempos não foram suficientes para as tarefas e explicações."},{"value":0,"label":"Nada efetivo","description":"O professor terminou a aula sem concluir a atividade principal. O tempo foi gasto quase totalmente com a organização da turma e explicações excessivas, sobrando pouco para a aprendizagem."}]'::jsonb, 'Gestão de Sala de Aula', 15, true, null),

('registro_apoio_presencial', 'gestao_participacao', 'A maioria dos alunos participa da aula', 'Engajamento coletivo e a capacidade do professor de converter o plano de aula em uma experiência compartilhada por todos.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"A maioria dos alunos participou ativamente durante toda a aula, com interações frequentes e espontâneas."},{"value":2,"label":"Efetivo","description":"A maioria dos alunos participou da aula na maior parte do tempo."},{"value":1,"label":"Pouco efetivo","description":"Apenas alguns alunos participaram ativamente, enquanto a maioria permaneceu passiva."},{"value":0,"label":"Nada efetivo","description":"A participação dos alunos foi mínima ou inexistente durante a aula."}]'::jsonb, 'Gestão de Sala de Aula', 16, true, null),

('registro_apoio_presencial', 'gestao_clima', 'O clima na sala de aula é de colaboração, respeito mútuo e favorável à aprendizagem', 'O respeito e a segurança para errar, especialmente quando está recuperando defasagens, apoia o desenvolvimento da aprendizagem.', 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"O ambiente é de colaboração e respeito mútuo. Os alunos se sentem seguros para errar e participar. O professor promove ativamente um clima positivo."},{"value":2,"label":"Efetivo","description":"O ambiente é respeitoso e favorável à aprendizagem na maior parte da aula."},{"value":1,"label":"Pouco efetivo","description":"O ambiente apresenta momentos de desrespeito ou dispersão que prejudicam parcialmente a aprendizagem."},{"value":0,"label":"Nada efetivo","description":"O ambiente é desfavorável à aprendizagem, com desrespeito frequente ou clima de tensão."}]'::jsonb, 'Gestão de Sala de Aula', 17, true, null),

('registro_apoio_presencial', 'gestao_respeito_conflito', 'O clima de respeito é fundamental nas intervenções docentes quando os estudantes estão dispersos ou em casos de conflito e indisciplina', null, 'rating', 0, 3, '[{"value":3,"label":"Muito efetivo","description":"O professor interveio de forma respeitosa e eficaz em situações de dispersão ou conflito, mantendo o clima favorável à aprendizagem."},{"value":2,"label":"Efetivo","description":"O professor interveio de forma adequada na maioria das situações de dispersão ou conflito."},{"value":1,"label":"Pouco efetivo","description":"O professor interveio em situações de dispersão ou conflito, mas de forma pouco eficaz ou inconsistente."},{"value":0,"label":"Nada efetivo","description":"O professor não interveio em situações de dispersão ou conflito, ou as intervenções foram inadequadas."}]'::jsonb, 'Gestão de Sala de Aula', 18, true, null),

('registro_apoio_presencial', 'gestao_evidencias', 'Registre as evidências referentes a este foco de observação', null, 'textarea', null, null, null, 'Gestão de Sala de Aula', 19, true, null),

-- DIMENSÃO: Obrigatórias (4 textarea)
('registro_apoio_presencial', 'obrig_aspectos_pratica', 'A partir da análise de evidências, quais aspectos da prática docente serão trabalhados na devolutiva?', null, 'textarea', null, null, null, 'Obrigatórias', 20, true, null),
('registro_apoio_presencial', 'obrig_perguntas_reflexao', 'Quais perguntas poderão nortear a reflexão do professor?', null, 'textarea', null, null, null, 'Obrigatórias', 21, true, null),
('registro_apoio_presencial', 'obrig_sugestoes', 'Quais sugestões serão oferecidas?', null, 'textarea', null, null, null, 'Obrigatórias', 22, true, null),
('registro_apoio_presencial', 'obrig_combinados', 'Quais combinados/encaminhamentos deseja realizar?', null, 'textarea', null, null, null, 'Obrigatórias', 23, true, null);

-- Insert form_config_settings for all programs
INSERT INTO public.form_config_settings (form_key, programas, min_optional_questions)
VALUES ('registro_apoio_presencial', ARRAY['escolas', 'regionais', 'redes_municipais']::programa_type[], 0)
ON CONFLICT (form_key) DO NOTHING;
